### ISSUE TITLE
goldcoin p2pool?

### ISSUE THREAD

**Issue by mousesport** [goldcoin/gldcoin#14]
Who run p2pool on goldcoin?

**Comment by microguy** [comment]
p2pool@inetrader.com

From: +ViktorSinitsyn 
Sent: Wednesday, May 10, 2017 4:08 AM
To: goldcoin/goldcoin 
Cc: Subscribed 
Subject: [goldcoin/goldcoin] goldcoin p2pool? (#14)

Who run p2pool on goldcoin?
