### ISSUE TITLE
Goldcoin Memory Issues / Memory Leak? Debian 8

### ISSUE THREAD

**Issue by daygle** [goldcoin/gldcoin#15]
I have successfully compiled Goldcoin in Debian 8 and after running Goldcoin I am noticing that it's consuming large amounts of RAM the longer I leave it running - in fact it can hog up to 13GB on my VPS!

When this happens I simply stop then start Goldcoin which simply releases the RAM.

Do you have any recommendations on how to reduce RAM usage.

It almost seems like this has a memory leak?

**Comment by akumaburn** [comment]
AFAIK Goldcoin will use about 2GB of ram and should not hover much above that. It is possible for the memory to inflate to between 11-22GB if a significant number of orphans are found. Is this your first sync of the blockchain? If so have you added the seed nodes we recommend to your config file?

**Comment by daygle** [comment]
Thanks for your reply, I'm running the wallet behind the mining pool gld.thecoin.pw. This mining pool has located a number of blocks.

What nodes do you recommend?

**Comment by akumaburn** [comment]
Try:

24.54.97.47
107.161.23.121
149.202.121.129

I also suggest if you haven't already to sync your clock to NTP time.

Let me know if you're still having issues.

**Comment by daygle** [comment]
Thanks mate... I'll let you know how it goes.

Are you able to provide guidance for the below settings I have in my goldcoin.conf file (maybe some are not required?):-

banscore=5
bantime=604800
checkpoints=1
daemon=1
dns=1
dnsseed=1
gen=0
maxconnections=8
par=1
server=1
shrinkdebugfile=1
testnet=0

**Comment by akumaburn** [comment]
try this instead:

rpcallowip=127.0.0.1
daemon=1
server=1
gen=0
maxconnections=12
dns=1
checkpoints=1
listen=1
dnsseed=1
banscore=50
bantime=14400

**Comment by daygle** [comment]
Thanks, I'll have an update in 12 to 24 hours. Let's see if the goldcoind behaves itself and doesn't consume a heap of memory.

**Comment by daygle** [comment]
Unfortunately it is still happening even with all the recommendations.

Surely others are also experiencing this? Maybe it happens to users that use the wallet to mine? I wonder if the Goldcoin 51% limitation is causing this as other wallet work without issues.

![408c69a2-4a7b-11e7-9318-28321a4a3e9f](https://cloud.githubusercontent.com/assets/5925233/26801057/ee7f5b02-4a7e-11e7-9cc0-ccf596a58800.png)

**Comment by akumaburn** [comment]
This is the first we've heard of it.. the only time I can think this might happen is if you took out some of the 51% code as part of the code queues up blocks for you with the minimum timestamps the 51% defense allows.

The only code change that I think might cause this is the code change that handles orphan restructuring of up to 11,000 blocks. But even then the blocks would need to be basically full for this to happen.

Does this happen with the linux version hosted on gldcoin.com? or only your compiled version?

**Comment by daygle** [comment]
At first I only had Goldcoin compiled on my Debian 8 production server - this was the server that experienced high memory usage.

I have tested even further by setting up a second goldcoin wallet on another VPS which only has Goldcoin compiled and is not used as a mining pool wallet. Guess what? memory usage is great - that said, as soon as I switch my mining pool to the wallet I get a huge memory increase.

You should be able to replicate yourself, the issue seems to only appear when the wallet is used to mine. This may be why other users have not reported the issue as only mining pool operators would experience the issue.

**Comment by akumaburn** [comment]
Are you using getwork or getblocktemplate?

**Comment by daygle** [comment]
I am using nomp as the stratum component for my mining pool, I beleive it uses getwork or getworktemplate - I think?

**Comment by Stouse49** [comment]
Currently I have an fastcoin daemon running on my Ubuntu 16.04 system and it is using 5.9 GB (virtual) 
 and 5.1 GB RESidence memory (as it processes a 2.5 GB Wallet).

My goldcoin daemon is not doing anything but syncing an empty wallet and is using 1.5GB of virtual and 0.7 GB of residence memory after running for 30 minutes. I compiled goldcoind on my system.

**Comment by akumaburn** [comment]
Would need to setup a test mining system of my own to be sure, I've tested mining before but only on testnet, didn't test memory then. Still we've not heard of memory leak issues from any GLD pool so far. We haven't touched the mining algorithm/functions themselves, only what blocks are accepted.

**Comment by Stouse49** [comment]
@daygle Can you post your ~/.goldcoin/debug.log file here and we can look for any warnings or errors that may help find the cause?

**Comment by daygle** [comment]
Thanks @Stouse49 - Yes, looks like your not mining with your wallet. So that is expected.

Happy to provide you my debug, that said I clear it every 15 minutes to improve speed - the bigger the file the slower the wallet performs. I'll upload in few minutes which will contain the last 10 - 15 minutes of debug.

**Comment by daygle** [comment]
[debug.txt](https://github.com/goldcoin/goldcoin/files/1053717/debug.txt)

As promised, please find attached the debug.log.

**Comment by Stouse49** [comment]
@daygle There is nothing in the log from my point of view that indicates a problem.

`CTxMemPool::accept() : accepted 77526d46150fcab24433ca856c577a5bb3668847961ca4b37daecd93dd93bf16 (poolsz 1)`

This line from your log tells us that the transaction memory pool has one transaction, which certainly wouldn't take up many GB's.

One thing I didn't notice in the log was any of these:
`ProcessBlock: ORPHAN BLOCK, prev=cc7a0d8dd9c5d4d76184`

I found some of these in my own debug.log, but I am not deleting the log every 15 minutes.

Your debug.log came much later than when the daemon started using all the extra memory.  My only suggestion would be to restart the daemon and let the debug.log keep growing while the memory usage grows and then we look at the debug.log.  During the start up time when the daemon starts to use a lot of memory, there may be something in the log that indicates why.  

We can also ask @d0gZpAw who runs http://inetrader.com:8221/static/ what he sees for memory usage.  He has two pools mining GoldCoin.

**Comment by d0gZpAw** [comment]
Just so happened to check the issues when I saw the mention.. Goldcoin P2Pool has been particularly active lately, so I can report goldcoind memory usage at different loads on similar VPS configurations.  Both VPS assigned 3GB RAM.

inetrader @ 1.8GH/s

![gld-inetrader](https://cloud.githubusercontent.com/assets/6202469/26818789/eea56bd6-4a50-11e7-89b5-9bf309279d19.png)

hashcube @ 400MH/s

![gld-hashcube](https://cloud.githubusercontent.com/assets/6202469/26818794/f6df6f4a-4a50-11e7-932a-0120d51311bd.png)

Neither of these nodes pay out to the local wallet.dat file, keeping filesize to a minimum. Hope that helps.  If anyone has more questions, let me know.

**Comment by daygle** [comment]
@d0gZpAw, obviously our pools are setup differently as your are running a P2Pool. Are you able to share your goldcoin.conf file?

**Comment by d0gZpAw** [comment]
@daygle, Nothing special in the goldcoin.conf, 
`server=1
listen=1
daemon=1
maxconnections=64
rpctimeout=30`
Also will note that I am not trimming debug.log either.

**Comment by daygle** [comment]
@d0gZpAw Thanks. Hmmmm rpctimeout is interesting.

Trimming the log file shouldn't cause memory issues.

**Comment by daygle** [comment]
@akumaburn you marked this issue as a bug, did you find out what is causing it?

Additionally it seems that Goldcoin doesn't support 'rpcthreads='. Just wondering if you have intentions to update the wallet in the future?

**Comment by akumaburn** [comment]
@daygle 

No sorry.

I do have the intent of moving code bases, right now 0.8.7.5 seems the likely candidate, expect a release around the end of this month the 0.10 release didn't have the best block interface, and the 0.13+ releases have a lot of extra stuff including segregated witness that I don't want without checking.

**Comment by daygle** [comment]
@akumaburn Thanks for getting back to me so fast.

I hope the new release comes soon rather than later, with the high memory usage I'm debating if I should continue hosting a Goldcoin mining pool.

**Comment by akumaburn** [comment]
@daygle 

Will try to be expedient but considering life and the Mac Port being bothersome, may take the full month to have it fully tested.

**Comment by daygle** [comment]
@akumaburn ok.

I am experimenting with the setup of goldcoin. Rather than sharing the wallet between mining and payouts I have separated the two - this is why I was asking about 'rpcthreads' a few comments ago.

Other than restarting goldcoind when memory gets too high there isn't really too much I can do.

**Comment by daygle** [comment]
@akumaburn have you made any recent changes on the back end? My wallet is no longer consuming loads of ram, and additionally I have noticed that the my mining pool isn't finding as many orphaned blocks.

Could this be related to issue #16 - was someone sending tons of small payments which in turn was causing high loads?

**Comment by d0gZpAw** [comment]
@daygle I only sent a few transactions, all fit within the 100kb transaction limit, which wouldn't put any extra load on the network.  You may be experiencing higher load due to increased orphan rate, which happens every time the difficulty is proportionally lower than new hashrate on the network.  There's also another quirk, referenced in issue #11 where the daemon will wait until the local time catches up to a valid block's timestamp `queueing until timestamp is valid`, which can also cause increased load.  I don't think anyone has figured out why blocks are getting submitted with timestamps in the future.  It is likely that moving your transactions to a separate wallet, not in use by the daemon, also reduced your load factor.

**Comment by chrysophylax69** [comment]
@daygle ... could you please contact me on skype - chrysophylax69 ... other coins with this same issue seem to be prevalent - and i would like to connect with you to discuss a couple of other things also ... i have no other way of contacting you ... id appreciate it greatly ...

#crysx

**Comment by daygle** [comment]
I believe the new Goldcoin wallet corrected the issues.

Closing case.
