### ISSUE TITLE
Transactions with many small inputs fail -- Coin Control options required.

### ISSUE THREAD

**Issue by d0gZpAw** [goldcoin/gldcoin#16]
When attempting to consolidate many small inputs into a larger input, Goldcoin wallet fails with 
`Error: Transaction creation failed.`
I am forced to attempt smaller and smaller transactions until the wallet can determine which inputs will fit into a transaction.   Unless I can find a script, or write my own raw transactions, I will be unable to spend most of the inputs, and large portion of the inputs will be consumed in transaction fees.  Adding Coin Control features, that have been included in Bitcoin-core and Litecoin-core for some time, would mitigate the need for creating raw transactions or splitting up transactions into many smaller amounts.  P2Pool users are often paid in small increments, and it takes many inputs to create a transaction that is worth the transaction fee.

**Comment by akumaburn** [comment]
Noted, the codebase is outdated as is. I do intend on updating it. I'm just not sure if we want the seg-wit stuff in the latest versions of litecoin. Irregardless, this is on my todo list, I'll see if I can get a version that is at least 0.8.x out within the month.

**Comment by Stouse49** [comment]
I can verify the issue that @d0gZpAw has stated, though I have experienced it with other coin wallets that have thousands of small transactions, many probably from mining.  GoldCoin probably has a 100KB max transaction size like many other coins and that is the limiting factor.

Coin control does give the user a better chance of sending out coins more efficiently in some cases and more so than the default coin selector that is part of the GoldCoin.  Its possible that the Default Coin Selector is better in upgraded versions of bitcoin/lightcoin code as well.

I also have had experience with writing scripts to transfer out coins from these wallets as well.  In some cases other coin wallets had much trouble in the transfer process and the coins were never sent or were delayed considerably.  

An upgrade is definitely a good idea.  I can help with testing and compiling on Mac and Linux systems.

**Comment by akumaburn** [comment]
Regarding coin-control, can anyone verify whether it is present in 0.8.7.5 of Bitcoin?
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.8.0.md

I noticed that they have coin-control listed, but I'm not certain as to what API features are necessary.. It seems Coin-control was only added to the GUI side of things in 0.9,

Please let me know what is required, if 0.8 is fine, then I can push the code to github soon, if 0.9 is needed, I will need to do more work.

**Comment by d0gZpAw** [comment]
@akumaburn I was only able to check Bitcoin v0.8.6-beta and there are no coin control options in the GUI.  Instead there is a python script that doesn't seem to let you select inputs within a specific address.  Without the GUI coin-control features, it can be almost impossible to select the right combination of inputs to fit a transaction with value greater than the fees required.  There are many p2pool users that will be unable to spend a considerable portion of their balance until these features are added.  I understand updating the codebase to 0.9 will take a while longer, and remain patient in the meantime.  Your efforts are much appreciated, thank you!
